build: update gradle to 7.4.0
junit-team/junit5-samples pull request #163
Opened 2022-03-05 01:31 UTC by chenrui333

Signed-off-by: Rui Chen <rui@chenrui.dev>

## Overview

- build: update gradle to 7.4.0

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

2022-03-05 12:05 UTC, marcphilipp approved these changes

2022-03-05 12:06 UTC, marcphilipp requested changes

2022-03-05 12:06 UTC, marcphilipp commented on junit5-jupiter-extensions/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.0-bin.zip
```suggestion
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
```

2022-03-05 16:37 UTC, chenrui333 commented on junit5-jupiter-extensions/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.0-bin.zip
Should be good now. 😅

2022-03-08 07:50 UTC, marcphilipp approved these changes
Thanks! 👍

2022-03-08 07:51 UTC, merged